global:
  scrape_interval: 15s # Her 15 saniyede bir hedeflerden veri almak
  evaluation_interval: 15s # Her 15 saniyede bir kural değerlendirmesi yapmak

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'geo-service'
    static_configs:
      - targets: ['app:3000']
    metrics_path: /metrics
    scheme: http
